name: GitHub Actions Demo - updated 2
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [pull_request]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Self sast-scan
      uses: AppThreat/sast-scan-action@master
      with:
        type: nodejs
      env:
        SCAN_ID: ${{ github.sha }}
        WORKSPACE: https://github.com/${{ github.repository }}/blob/${{ github.sha }}
        GITHUB_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }} 
    
    - name: Upload scan reports
      uses: actions/upload-artifact@v1.0.0
      with:
        name: sast-scan-reports
        path: reports