name: GitHub Actions Demo - updated 2
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest
    name: Jira Auth
    steps:
    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: https://daywisonleal.atlassian.net/
        JIRA_USER_EMAIL: daywison.leal@gmail.com  
        JIRA_API_TOKEN: ATATT3xFfGF0hBp2ly_tIKiXvxNCs9CHZRuMaEmufFsDS-PkrPJT0arCXk_nPolNP4ryT2u07659Gxg5Dkbp_Er3p0Laq7PHTeNrr2GzaTpwlgorMyo6KL9wuAcdhqsxyVsINk4dBUm_C-l7OzPHVhGK1nQASA79IjnMNyBVkHMrSU0R90tu6GU=BB0D9BCD

    - name: Jira TODO
      uses: atlassian/gajira-todo@v3
      with:
        project: GA
        issuetype: Task
        description: Created automatically via GitHub Actions
      env:
        GITHUB_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}